// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr4kLEjj4m4xXDMf7W_YefEvI62xvAG1Q',
    appId: '1:401484168460:web:f7ec65f8c03f781d729d29',
    messagingSenderId: '401484168460',
    projectId: 'mnemo-fe6cf',
    authDomain: 'mnemo-fe6cf.firebaseapp.com',
    storageBucket: 'mnemo-fe6cf.appspot.com',
    measurementId: 'G-24B3RJH6YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq3vId_l5rQlyA3gKpoOlxx6c92djLdvA',
    appId: '1:401484168460:android:d92be02ffc81a6d9729d29',
    messagingSenderId: '401484168460',
    projectId: 'mnemo-fe6cf',
    storageBucket: 'mnemo-fe6cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvB3mMjqzaDouXDD0EHnvnfuQzYw22xQ0',
    appId: '1:401484168460:ios:429aac537d4f96d7729d29',
    messagingSenderId: '401484168460',
    projectId: 'mnemo-fe6cf',
    storageBucket: 'mnemo-fe6cf.appspot.com',
    iosClientId: '401484168460-siq841g3kh30ssl2dumsdu24hr8ng58f.apps.googleusercontent.com',
    iosBundleId: 'com.example.mnemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvB3mMjqzaDouXDD0EHnvnfuQzYw22xQ0',
    appId: '1:401484168460:ios:f2a6e19b7d4a3eb9729d29',
    messagingSenderId: '401484168460',
    projectId: 'mnemo-fe6cf',
    storageBucket: 'mnemo-fe6cf.appspot.com',
    iosClientId: '401484168460-eqvmsmq4pva3dcd5uarcmc2ahfi7a0d2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mnemo.RunnerTests',
  );
}
